version: '3.7'

services:
  node:
    image: node:aui
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always
  node1:
    image: node:aui
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/app
      - /app/node_modules
    ports:
      - 3001:3000
    restart: always
  node2:
    image: node:aui
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/app
      - /app/node_modules
    ports:
      - 3002:3000
    restart: always
